assets_eq_global = {
    #'ACWI',
    'US',
    'Canada',
    'Mexico',
    'Peru',
    'Brazil',
    'Argentina',
    'UK',
    'Spain',
    'Germany',
    'Italy',
    'Egypt',
    'India',
    'Africa',
    'SouthAfrica',
    'Russia',
    'Korea',
    'Japan',
    'China',
    'Singapore',
    'Australia',
    'Austria',
    'Belgium',
    'France',
    'HongKong',
    'Malaysia',
    'Netherland',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Vietnam',
    'Poland',
    'NewZealand',
    'Greece',
    'Norway',
    'Indonesia',
    'Philip',
    'Thailand',
    'Turkey',
    'Chile',
    'Colombia',
    'Saudi',
    #'BND_US_Interm',
    #'BND_US_Long',
}


mapper = {
    'arirang_esg':                       'ESG_kr', 
    'arirang_lowvol':                    'LowVol_kr', 
    'arirang_mtum':                      'Growth_kr', 
    'arirang_qual':                      'Quality_kr', 
    'arirang_value':                     'Value_kr', 
    'kodex200':                          'K200_2', 
    'kodex200_ew':                       'EW_kr_2', 
    'kodex200_midcap':                   'Midcap_kr', 
    'kodex_dvd_growth':                  'DvdGrowth_kr_2', 
    'kodex_dvd_high':                    'HighDvd_kr', 
    'kodex_ksp':                         'KSP_2', 
    'kodex_ktb3y':                       'KTB3Y', 
    'kodex_lev':                         'K200L2', 
    'kodex_lowvol':                      'LowVol_kr_2', 
    'kodex_mtum_plus':                   'Momentum_kr', 
    'kodex_qual_plus':                   'Quality_kr_2', 
    'kodex_turnaround':                  'Turnaround_kr', 
    'kodex_value_plus':                  'Value_kr_2', 
    'kosef_ktb10y':                      'KTB10Y', 
    'kosef_ktb10y_lev':                  'KTB10YL', 
    'tiger200':                          'K200', 
    'tiger200_ew':                       'EW_kr', 
    'tiger_beta_plus':                   'HighBeta_kr', 
    'tiger_contrarian':                  'Contrarian_kr', 
    'tiger_dvd_growth':                  'DvdGrowth_kr', 
    'tiger_dvd_sustainable':             'DvdSust_kr', 
    'tiger_ksp':                         'KSP', 
    'tiger_ksp_dvd_high':                'HighDvd_kr_2', 
    'tiger_lev':                         'K200L', 
    'tiger_lowvol':                      'LowVol_kr_3', 
    'tiger_mtum':                        'MomentumGrowth_kr', 
    'tiger_pref':                        'Pref_kr', 


    'xlb_spdr_material':                 'Material', 
    'xly_spdr_consumer_disc':            'ConsumerDiscretionary', 
    'xlp_spdr_consumer_stp':             'ConsumerStaples', 
    'xle_spdr_energy':                   'Energy', 
    'xlf_spdr_financial':                'Financial', 
    'xlv_spdr_healthcare':               'Healthcare', 
    'xli_spdr_industry':                 'Industry', 
    'iyr_ishares_reit':                  'REIT', 
    'xlk_spdr_tech':                     'Tech',
    'iyz_ishares_telcom':                'Telcom', 
    'xlu_spdr_util':                     'Utility', 


    'spy_spdr_us':                       'US', 
    'ewc_ishares_canada':                'Canada', 
    'eww_ishares_mexico':                'Mexico', 
    'epu_ishares_peru':                  'Peru', 
    'ewz_ishares_brazil':                'Brazil', 
    'argt_globalx_argentina':            'Argentina', 
    'ewu_ishares_uk':                    'UK', 
    'ewp_ishares_spain':                 'Spain', 
    'ewg_ishares_germany':               'Germany', 
    'ewi_ishares_italy':                 'Italy', 
    'egpt_vaneck_egypt':                 'Egypt', 
    'inda_ishares_india':                'India', 
    'afk_vaneck_africa':                 'Africa', 
    'eza_ishares_south_africa':          'SouthAfrica', 
    'rsz_vaneck_russia':                 'Russia', 
    'ewy_ishares_skorea':                'Korea', 
    'ewj_ishares_jp':                    'Japan', 
    'mchi_ishares_china':                'China', 
    'ews_ishares_singapore':             'Singapore', 
    'ewa_ishares_australia':             'Australia', 
    'ewo_ishares_austria':               'Austria', 
    'ewk_ishares_belgium':               'Belgium', 
    'ewq_ishares_fr':                    'France', 
    'ewh_ishares_hk':                    'HongKong', 
    'ewm_ishares_malaysia':              'Malaysia', 
    'ewn_ishares_netherland':            'Netherland', 
    'ewd_ishares_sweden':                'Sweden', 
    'ewl_ishares_switzerland':           'Switzerland', 
    'ewt_ishares_taiwan':                'Taiwan', 
    'vnm_vaneck_vietnam':                'Vietnam', 
    'epol_ishares_poland':               'Poland', 
    'enzl_ishares_newzealand':           'NewZealand', 
    'grek_globalx_greece':               'Greece', 
    'norw_globalx_norway':               'Norway', 
    'eido_ishares_indonesia':            'Indonesia', 
    'ephe_ishares_philip':               'Philip', 
    'thd_ishares_thailand':              'Thailand', 
    'tur_ishares_turkey':                'Turkey', 
    'ech_ishares_chile':                 'Chile', 
    'gxg_globalx_colombia':              'Colombia', 
    'ksa_ishares_saudi':                 'Saudi', 


    'qual_ishares_qual':                 'Quality', 
    'ive_ishares_value':                 'Value', 
    'ivw_ishares_growth':                'Growth', 
    'mtum_ishares_mtum':                 'Momentum', 
    'eemo_pshares_mtum_em':              'Momentum_EM', 
    'vig_vanguard_dvd_apprec':           'DvdApprec', 
    'dvy_ishares_high_dvd':              'HighDvd', 
    'sphb_pshares_high_beta':            'HighBeta', 
    'uslb_pshares_low_beta':             'LowBeta', 
    'splv_pshares_low_vol':              'LowVol', 
    'cowz_pacer_fcf':                    'HighFCF', 
    'def_pshares_defensive':             'Defensive', 
    'eusa_ishares_ew':                   'EW', 
    'csm_pshares_130_30':                '130/30', 
    'she_spdr_gender':                   'Gender', 
    'qyld_horizons_covered_call':        'CoveredCall', 
    'gvip_gs_hedgefund_hold':            'HedgefundHold', 
    'moat_vaneck_moat':                  'Moat', 
    'ftls_firstrust_long_short':         'LongShort', 
    'wtmf_wisdomtree_mgd_futs':          'ManagedFut', 
    'mna_iq_m&a':                        'M&A', 
    'susa_ishares_esg':                  'ESG', 
    'ipo_renaissance_ipo':               'IPO', 
    'know_direxion_insider':             'Insider', 
    'nfo_pshares_insider':               'Insider2', 
    'iwm_ishares_smallcap':              'SmallCap', 
    'xrlv_pshares_xrate_sen_lowvol':     'Xrate_Lowvol', 


    'uup_pshares_usd_up':                'USD_UP', 
    'fxy_cshares_jpy':                   'JPY', 
    'fxe_cshares_eur':                   'EUR', 
    'fxa_cshares_aud':                   'AUD', 
    'fxc_cshares_cad':                   'CAD', 
    'fxf_cshares_chf':                   'CHF', 
    'fxb_cshares_gbp':                   'GBP', 
    'udn_pshares_usd_down':              'USD_DOWN', 


    'dbc_pshares_comdty':                'Comdty', 
    'uso_uns_wti':                       'WTI', 
    'gld_spdr_gold':                     'Gold', 
    'slv_ishares_silver':                'Silver', 
    'dba_pshares_agriculture':           'Agriculture', 
    'ung_uns_ngas':                      'NatGas', 
    'dbe_pshares_energy':                'Engy', 
    'dbb_pshares_bmetal':                'BaseMetal', 
    'gltr_etfs_pmetal':                  'PrecMetal', 


    'agg_ishares_us_bd_agg':             'BND_US_AGG', 
    'bil_spdr_us_tbil':                  'BND_US_Tbill', 
    'shy_ishares_us_bd_short':           'BND_US_Short', 
    'ief_ishares_us_bd_interm':          'BND_US_Interm', 
    'tlt_ishares_us_bd_long':            'BND_US_Long', 
    'tip_ishares_us_tip':                'BND_US_TIP', 
    'lqd_ishares_us_ig':                 'BND_US_IG', 
    'hyg_ishares_us_hy':                 'BND_US_HY', 
    'mbb_ishares_us_mbs':                'BND_US_MBS', 
    'mub_ishares_us_muni':               'BND_US_Muni', 
    'bkln_pshares_us_bankloan':          'BND_US_Bankloan', 
    'cwb_spdr_us_cb':                    'BND_US_CB', 
    'hyd_vaneck_us_hy_muni':             'BND_US_HY_Muni', 
    'pff_ishares_us_pref':               'BND_US_Pref', 


    'bwx_spdr_global_sov_loc':           'BND_GlobalSov_loc', 
    'wip_spdr_global_tip_loc':           'BND_GlobalTip_loc', 
    'bndx_vangard_global_sov_loc_h':     'BND_GlobalSov_loch', 
    'igov_ishares_developed_sov_loc':    'BND_DevSov_loc', 
    'flot_ishares_developed_float_usd':  'BND_DevFloat_usd', 
    'picb_pshares_developed_ig_loc':     'BND_DevIG_loc', 
    'hyxu_ishares_developed_hy_loc':     'BND_DevHY_loc', 
    'emb_ishares_em_sov_usd':            'BND_EmSov_usd', 
    'emlc_vaneck_em_sov_loc':            'BND_EmSov_loc', 
    'emhy_ishares_em_hy_usd':            'BND_EmHy_usd', 
    'dsum_pshares_china_credit_loc':     'BND_ChinaCredit_loc', 
    '114260_kodex_kr_bd_short_usd':      'BND_KR_Short_usd', 
    '148070_kosef_kr_bd_interm_usd':     'BND_KR_Interm_usd', 
    '167860_kosef_kr_bd_interm_lev_usd': 'BND_KR_Interm_lev_usd', 


    'acwi_ishares_acwi':                 'ACWI', 
    'vti_vanguard_us_total':             'US_Total', 
    'veu_vanguard_global':               'Global', 
    'iev_ishares_europe':                'EU', 
    'efa_ishares_developed':             'Developed', 
    'eem_ishares_em':                    'EM', 
    'aaxj_ishares_asia_xjp':             'Asia_xJp', 
    'bkf_ishares_bric':                  'BRIC', 
    'fm_ishares_frontier':               'Frontier', 
    'ilf_ishares_latam':                 'Latam', 


    'vnq_vanguard_us_reit':              'REIT_US', 
    'rwx_spdr_global_reit':              'REIT_Global', 
    'rem_ishares_us_mortgage_reit':      'REIT_US_Mort', 
}